const SYMBOLS = {
  PostNodeSummaries: Symbol.for('PostNodeSummaries'),
  PostEdgeSummaries: Symbol.for('PostEdgeSummaries'),
  PostGraph: Symbol.for('PostGraph'),
  PostNodeNewable: Symbol.for('PostGraph.NodeNewable'),
  EBAdmin: Symbol.for('EBAdmin'),
  EBGraphVis: Symbol.for('EBGraphVis'),
  PostGraphAppendNodeNotifier: Symbol.for('PostGraphAppendNodeNotifier'),
  PostGraphAppendNodeObserver: Symbol.for('PostGraphAppendNodeObserver'),
  PostGraphDeleteNodeNotifier: Symbol.for('PostGraphDeleteNodeNotifier'),
  PostGraphDeleteNodeObserver: Symbol.for('PostGraphDeleteNodeObserver'),
  NewDialogOkTask: Symbol.for('NewDialogOkTask'),
  NewDialogOkDrawNode: Symbol.for('NewDialogOkDrawNode'),
  NewDialogOkHideNode: Symbol.for('NewDialogOkHideNode'),
  NewDialogOkHandler: Symbol.for('NewDialogOkHandler'),
  NewDialogCloseHandler: Symbol.for('NewDialogCloseHandler'),
  EBNewDialog: Symbol.for('EBNewDialog'),
  EBNewDialogBody: Symbol.for('EBNewDialogBody'),
  EBNewDialogPopup: Symbol.for('EBNewDialogPopup'),
  ContextMenuNewSelection: Symbol.for('ContextMenuNewSelection'),
  ContextMenuPopup: Symbol.for('ContextMenuPopup'),
  ContextMenuHandler: Symbol.for('ContextMenuHandler'),
  NewNodeModel: Symbol.for('NewNodeModel'),
  NewNodeInput: Symbol.for('NewNodeInput'),
  NewNodeInputHandler: Symbol.for('NewNodeInputHandler'),
  NodeContextMenuPopup: Symbol.for('NodeContextMenuPopup'),
  DeleteSelection: Symbol.for('DeleteSelection'),
  NodeContextMenuHandler: Symbol.for('NodeContextMenuHandler'),
  NodeContextMenuSelectedId: Symbol.for('NodeContextMenuSelectedId'),
  EBEditorPopup: Symbol.for('EBEditorPopup'),
  EBEditorPopupBody: Symbol.for('EBEditorPopupBody'),
  EBEditorOkButton: Symbol.for('EBEditorOkButton'),
  EBEditorCancelButton: Symbol.for('EBEditorCancelButton'),
};

export {
  SYMBOLS,
};
